export const nutritionPhases = [
  { id: 'breakfast', kicker: 'RÁNO', title: 'Snídaně', subtitle: 'Základ pro sportovní den', rule: 'Větší jídlo s výrazným podílem sacharidů. Přidej bílkovinu a tekutiny podle chuti a tolerance.' },
  { id: 'early', kicker: 'PŘED VÝKONEM', title: '1–2 h před zápasem', subtitle: 'Lehká sacharidová svačina', rule: 'Lehká, známá a dobře stravitelná volba. Jedna potravina nebo malá kombinace může úplně stačit.' },
  { id: 'close', kicker: 'TĚSNĚ PŘED', title: '30–60 min před', subtitle: 'Malé doplnění energie', rule: 'Není potřeba velká svačina. Jedna lehká sacharidová volba může být dostačující.' },
  { id: 'between', kicker: 'TURNaj', title: 'Mezi zápasy', subtitle: 'Podle času do dalšího zápasu', rule: 'Krátká pauza = lehčí volba. Při delší pauze je prostor pro větší svačinu nebo malé jídlo.' },
  { id: 'recovery', kicker: 'REGENERACE', title: 'Po posledním zápase', subtitle: 'Energie + bílkoviny + tekutiny', rule: 'Po výkonu kombinuj sacharidy a zdroj bílkovin. Velikost přizpůsob hladu a tomu, kdy bude další jídlo.' },
]

const F = (id, name, image, tags, phases, note) => ({ id, name, image, tags, phases, note })

export const foods = [
  F('banana','Banán','1F34C',['carb','easy','fruit'],['breakfast','early','close','between'],'snadno stravitelný'),
  F('apple','Jablko','1F34E',['carb','fruit'],['breakfast','early','between'],'podle tolerance'),
  F('pear','Hruška','1F350',['carb','fruit'],['breakfast','early','between'],'podle tolerance'),
  F('grapes','Hroznové víno','1F347',['carb','easy','fruit'],['breakfast','early','close','between'],'praktické do krabičky'),
  F('orange','Pomeranč','1F34A',['carb','fruit'],['breakfast','early','between'],'lehká ovocná volba'),
  F('strawberry','Jahody','1F353',['carb','fruit'],['breakfast','early','between'],'lehká porce'),
  F('blueberries','Borůvky','1FAD0',['carb','fruit'],['breakfast','early','between'],'lehká porce'),
  F('melon','Meloun','1F349',['carb','easy','fruit'],['breakfast','early','between'],'osvěžující volba'),
  F('mango','Mango','1F96D',['carb','easy','fruit'],['breakfast','early','between'],'sladké ovoce'),
  F('kiwi','Kiwi','1F95D',['carb','fruit'],['breakfast','early','between'],'lehká ovocná volba'),
  F('peach','Broskev','1F351',['carb','fruit'],['breakfast','early','between'],'podle tolerance'),
  F('applesauce','Ovocná přesnídávka','1F963',['carb','easy'],['early','close','between'],'praktická na cestu'),
  F('raisins','Rozinky','1FAD0',['carb','easy'],['early','close','between'],'koncentrovaný zdroj sacharidů'),
  F('pretzels','Preclíky','1F968',['carb','easy'],['breakfast','early','close','between'],'lehké sacharidy'),
  F('ricecakes','Rýžové chlebíčky','1F358',['carb','easy'],['breakfast','early','close','between'],'lehké a křupavé'),
  F('crackers','Krekry','1F35A',['carb','easy'],['early','close','between'],'praktická svačina'),
  F('toast-honey','Toast + med','1F35E',['carb','easy'],['breakfast','early','close','between'],'rychlý zdroj sacharidů'),
  F('toast-jam','Toast + džem','1F35E',['carb','easy'],['breakfast','early','close','between'],'jednoduchá klasika'),
  F('roll-jam','Pečivo + džem','1F956',['carb','easy'],['breakfast','early','between'],'jednoduchá svačina'),
  F('bread-honey','Rohlík + med','1F35E',['carb','easy'],['breakfast','early','close','between'],'lehká sacharidová volba'),
  F('bagel','Bagel','1F96F',['carb'],['breakfast','early','between'],'větší zdroj energie'),
  F('cereal','Cereálie + mléko','1F963',['carb','protein'],['breakfast','early'],'spíš s odstupem'),
  F('oatmeal','Ovesná kaše','1F963',['carb','protein'],['breakfast'],'větší snídaně'),
  F('pancakes','Palačinky + ovoce','1F95E',['carb'],['breakfast'],'větší snídaně'),
  F('muesli','Müsli + jogurt','1F963',['carb','protein'],['breakfast'],'snídaně s odstupem'),
  F('rice-porridge','Rýžová kaše','1F35A',['carb'],['breakfast','early'],'lehčí než některá celozrnná jídla'),
  F('sandwich','Lehký sendvič','1F96A',['carb','protein'],['breakfast','between','recovery'],'při delší pauze'),
  F('turkey-sandwich','Sendvič s krůtím masem','1F96A',['carb','protein'],['breakfast','between','recovery'],'větší svačina'),
  F('cheese-bread','Pečivo + sýr','1F35E',['carb','protein'],['breakfast','between','recovery'],'spíš s větším odstupem'),
  F('wrap','Lehká tortilla','1FAD3',['carb','protein'],['breakfast','between','recovery'],'větší svačina'),
  F('yogurt-fruit','Jogurt + ovoce','1F95B',['carb','protein'],['breakfast','between','recovery'],'když je více času'),
  F('yogurt','Jogurt','1F95B',['protein'],['breakfast','between','recovery'],'zdroj bílkovin'),
  F('skyr-fruit','Skyr + ovoce','1F95B',['carb','protein'],['breakfast','between','recovery'],'sacharidy + bílkovina'),
  F('milk','Mléko','1F95B',['protein'],['breakfast','recovery'],'doplněk k jídlu'),
  F('chocolate-milk','Kakaové mléko','1F95B',['carb','protein'],['between','recovery'],'praktická regenerace'),
  F('rice','Rýže','1F35A',['carb'],['breakfast','between','recovery'],'větší jídlo'),
  F('rice-chicken','Rýže + kuře','1F35A',['carb','protein'],['between','recovery'],'větší jídlo'),
  F('pasta','Těstoviny + rajčatová omáčka','1F35D',['carb'],['breakfast','between','recovery'],'větší jídlo'),
  F('pasta-chicken','Těstoviny + kuře','1F35D',['carb','protein'],['between','recovery'],'větší jídlo'),
  F('potato','Brambory','1F954',['carb'],['breakfast','between','recovery'],'větší jídlo'),
  F('banana-bread','Banánový chléb','1F35E',['carb'],['breakfast','early','between'],'praktická svačina'),
  F('muffin','Muffin','1F9C1',['carb'],['breakfast','early','between'],'spíš při delší pauze'),
  F('cereal-bar','Cereální tyčinka','1F36B',['carb','easy'],['early','between'],'praktická na turnaj'),
  F('fruit-pouch','Ovocná kapsička','1F963',['carb','easy'],['early','close','between'],'snadná konzumace'),
  F('juice','Malý džus','1F9C3',['carb','easy'],['close','between'],'rychlý zdroj sacharidů'),
  F('smoothie','Ovocné smoothie','1F964',['carb'],['breakfast','early','between'],'vhodné, když se pevné jídlo hůře snáší'),
  F('egg-bread','Vejce + pečivo','1F95A',['carb','protein'],['breakfast','recovery'],'spíš mimo těsný předvýkonový čas'),
  F('hummus-bread','Pečivo + hummus','1F35E',['carb','protein'],['breakfast','between','recovery'],'větší svačina'),
]

export const phaseGuidance = {
  breakfast: { requireCarb: true, preferProtein: false, maxItems: 5 },
  early: { requireCarb: true, preferProtein: false, maxItems: 3 },
  close: { requireCarb: true, preferProtein: false, maxItems: 2 },
  between: { requireCarb: true, preferProtein: false, maxItems: 4 },
  recovery: { requireCarb: true, requireProtein: true, maxItems: 5 },
}
